### ISSUE TITLE
Can Arduino Uno Wifi rev2 connect to Xbox Wireless (model 1914, 3 buttons)?

### ISSUE THREAD

**Issue by OscarSheng** [ricardoquesada/bluepad32-arduino#13]
This board is on the support list. But model 1914 only support BLE and I saw ["BLE commands are NOT supported"](https://bluepad32.readthedocs.io/en/latest/plat_nina/).
I ran the controller example, but they don't connect. Is it because I need to flash Bluepad32 firmware first? Or they just not compatible.

**Comment by ricardoquesada** [comment]
oh yeah... you need to flash the firmware first... otherwise it simply won't work.

Model 1914 is supported.
