### ISSUE TITLE
New version 2.4.0 doesn't work with Arduino iot 33

### ISSUE THREAD

**Issue by nico7885** [ricardoquesada/bluepad32-arduino#4]
New version 2.4.0 doesn't work with Arduino iot 33, tested with switch controller.
The CheckFirmwareVersion not return the version (blank).

**Comment by ricardoquesada** [comment]
mmm... weird... I don't recall changing anything in the Nina backend... but everything is possible.

Any chance that you can test it with the latest build. Pre-compiled binaries are here:
https://gitlab.com/ricardoquesada/bluepad32/-/jobs/1939970798/artifacts/browse/tools/fw/artifacts/
?

Thanks!

**Comment by nico7885** [comment]
No it gives the same thing:
- CheckFirmwareVersion not return the version (blank) after upload new version pre-compiled
- With the example gamepad.ino, the controller can connect but I can't get info from the serial monitor (same thing),  commands do not seem to respond (setRumble do nothing)

**Comment by ricardoquesada** [comment]
weird... are you using the unmodified code from the Examples ?
The code should look something like this:

```c
void setup() {
  // Initialize serial
  Serial.begin(9600);
  while (!Serial) {
    // wait for serial port to connect.
    // You don't have to do this in your game. This is only for debugging
    // purposes, so that you can see the output in the serial console.
    ;
  }

  String fv = BP32.firmwareVersion();
  Serial.print("Firmware version installed: ");
  Serial.println(fv);
```


I've just tested it, and it works Ok:
![Screenshot_20220107_095955](https://user-images.githubusercontent.com/232330/148586781-d5dd5ddd-9fdc-4560-a35e-28efd76e97d9.png)

**Comment by ricardoquesada** [comment]
and just to confirm, the board that you are using is "Arduino Nano 3.3 IoT", correct?
(I'm using that one, and it works oK)

**Comment by nico7885** [comment]
Yes unmodified example code, arduino nano iot 33, no problem with version 2.3.0

I have a second chip, I will redo the tests.

**Comment by nico7885** [comment]
New chip arduino nano iot 33 , same thing!

Version 2.3.0 work
Version 2.4.0 not work

**Comment by ricardoquesada** [comment]
thanks.... yes, I was able to reproduce it.
When I compile it myself, using just `idf.py build` + `idf.py flash` it works, but the binaries generated by the builder are broken...

investigating...

**Comment by nico7885** [comment]
Happy to post a real problem and not waste your time.

**Comment by ricardoquesada** [comment]
fixed here: https://gitlab.com/ricardoquesada/bluepad32/-/commit/6d5ce97f5921d4417cf1e36c5643590b05caf6e0

Let's wait for the builder for finish... but the new binaries should be Ok.
https://gitlab.com/ricardoquesada/bluepad32/-/jobs/1954624275

**Comment by ricardoquesada** [comment]
I confirm that the latest build work Ok. Please download it from here:
https://gitlab.com/ricardoquesada/bluepad32/-/jobs/1954624275/artifacts/raw/tools/fw/artifacts/bluepad32-nina-6d5ce97.tar.gz

**Comment by ricardoquesada** [comment]
closing the loop. I've just release v2.5 with working binaries:
https://gitlab.com/ricardoquesada/bluepad32/-/tags/release_2.5.0
