### ISSUE TITLE
Incorrect Bluetooth address when multiple devices connected

### ISSUE THREAD

**Issue by nimice** [ricardoquesada/bluepad32-arduino#5]
**Prerequisites:**
- No device connected.

**Stimuli:**
- Connect one device with BT address X.
- Connect another device with BT address Y.

**Response:**
- When onConnectedGamepad is called for device X, the BT address for device X is used. **OK**
- When onConnectedGamepad is called for device Y, the BT address for device X is used. **NOK**

**Expected response:**
- The correct BT address is seen in onConnectedGamepad so that functionality can be built towards a specific device.

**Comment by ricardoquesada** [comment]
which  bluepad32-arduino library version are you using? which bluepad32 FW version are you using?

**Comment by nimice** [comment]
bluepad32-arduino library version is **1.1.4**
bluepad32 FW version is **3.5.2**

**Comment by ricardoquesada** [comment]
Fixed in 1.1.5.
