### ISSUE TITLE
Moving PS5 controller away from ESP32 cause unhandled Exception 

### ISSUE THREAD

**Issue by gunnicus** [ricardoquesada/bluepad32-arduino#6]
Hi, 
I connected a PS5 controller to ESP32, it is working fine unless I walk away with the PS5 controller from the ESP32. The issue starts to happen when the PS5 controller 6 meters away from the ESP32.

What happened:
I'm using 'Controller' from example. Upload Controller to ESP32.
![image](https://github.com/ricardoquesada/bluepad32-arduino/assets/4023477/6c4dd0ae-408a-419b-9f23-2da44930778c)

Pair PS5 controller with ESP32
Take PS5 controller about 6 memters away from ESP32, turn myself around make sure my body is between the PS5 controller and the ESP32's direction. Keep walking untill abount 10 meters away from ESP32, the PS5 controller turned off itself.

Below error happened in ESP32

FEX 0 0
FEX 0 0
FEX 7 0
ASSERT_PARAM(0 7), in ld_acl.c at line 1772
Guru Meditation Error: Core  0 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x4008fed4: 00f01d00 00004136 f01d0000
Core  0 register dump:
PC      : 0x4008fedb  PS      : 0x00060f34  A0      : 0x8008573e  A1      : 0x3ffc1f50  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000007  A5      : 0x3ff9cd42  
A6      : 0x000006ec  A7      : 0xfffffffb  A8      : 0x8000814b  A9      : 0x3ffc1ec0  
A10     : 0x00000000  A11     : 0x3ffc1ee4  A12     : 0x3ffc1e8f  A13     : 0x00000032  
A14     : 0x00000000  A15     : 0x3ffc1e95  SAR     : 0x00000004  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000000  LBEG    : 0x40090f09  LEND    : 0x40090f19  LCOUNT  : 0xfffffffe  

Backtrace: 0x4008fed8:0x3ffc1f50 0x4008573b:0x3ffc1f70 0x400327cb:0x3ffc1f90 0x40087bb5:0x3ffc1fd0 0x40087e89:0x3ffc1ff0 0x4008bde6:0x3ffc2020 0x4008c8af:0x3ffc2040 0x400850be:0x3ffc2060 0x400853dd:0x3ffc2080 0x400853bf:0x00000000 |<-CORRUPTED

ELF file SHA256: 60dedc08e98be6b0

Rebooting...

**Comment by ricardoquesada** [comment]
closing as dup of this one:
https://github.com/ricardoquesada/bluepad32/issues/43
